interface CommandUsageInterface {
    id?: number;
    command_id?: number;
    createdByUid?: number;
    name?: string;
    description?: string;
    executable_path?: string;
    arguments?: string;
    output_capturing_mode: string | undefined;
    output_filename?: string;
    output_parser?: string;
}

export { CommandUsageInterface };

/**
 * Autogenerated file, do not edit manually. @see https://github.com/reconmap/model-definitions
 */
const CommandUsage: CommandUsageInterface = {
    output_capturing_mode: "none",
};

export default CommandUsage;
