
interface Command {

	id?: number;
	creator_uid?: number;
	name?: string;
	description?: string;
	more_info_url?: string;
	tags?: string;
}

export { Command };


/**
 * Autogenerated file, do not edit manually. @see https://github.com/reconmap/model-definitions
 */
const defaultCommand : Command = {


}

export default defaultCommand;
