
interface CommandInterface {

	id?: number;
	creator_uid?: number;
	name?: string;
	description?: string;
	more_info_url?: string;
	tags?: string;
}


/**
 * Autogenerated file, do not edit manually. @see https://github.com/reconmap/model-definitions
 */
const Command : CommandInterface = {


}

export default Command;
