
interface CustomField {

	id?: number;
	parent_type?: string;
	name?: string;
	label?: string;
	kind?: string;
	config?: string;
}

export { CustomField };


/**
 * Autogenerated file, do not edit manually. @see https://github.com/reconmap/model-definitions
 */
const defaultCustomField : CustomField = {


}

export default defaultCustomField;
