
interface Document {

	user_id?: number;
	visibility: string | undefined;
	parent_id?: number;
	parent_type?: string;
	content?: string;
	title?: string;
}

export { Document };


/**
 * Autogenerated file, do not edit manually. @see https://github.com/reconmap/model-definitions
 */
const defaultDocument : Document = {

	visibility: 'private',

}

export default defaultDocument;
