interface UserInterface {
    id?: number;
    createdAt?: string;
    updatedAt?: string;
    last_login_ts?: string;
    subject_id?: string;
    active?: boolean;
    mfa_enabled: boolean | undefined;
    first_name: string | undefined;
    last_name: string | undefined;
    full_name?: string;
    short_bio?: string;
    username: string | undefined;
    email: string | undefined;
    timezone: string | undefined;
    preferences: any | undefined;
    role?: string;
}

export { UserInterface };

/**
 * Autogenerated file, do not edit manually. @see https://github.com/reconmap/model-definitions
 */
const User: UserInterface = {
    active: true,
    mfa_enabled: false,
    full_name: "",
    role: undefined,

    first_name: undefined,
    last_name: undefined,
    username: undefined,
    email: undefined,
    timezone: undefined,
    preferences: undefined,
};

export default User;
