
interface User {

	id?: number;
	insert_ts?: string;
	update_ts?: string;
	last_login_ts?: string;
	subject_id?: string;
	active?: boolean;
	mfa_enabled: boolean | undefined;
	full_name: string | undefined;
	short_bio?: string;
	username: string | undefined;
	email: string | undefined;
	timezone: string | undefined;
	preferences: any | undefined;
	role?: string;
}

export { User };


/**
 * Autogenerated file, do not edit manually. @see https://github.com/reconmap/model-definitions
 */
const defaultUser : User = {

	active: true,
	mfa_enabled: false,
	role: undefined,

	full_name: undefined,
	username: undefined,
	email: undefined,
	timezone: undefined,
	preferences: undefined,
}

export default defaultUser;
