
interface Vault {

	id?: number;
	insert_ts?: string;
	update_ts?: string;
	project_id?: number;
	type: string | undefined;
	name?: string;
	value?: string;
	note?: string;
}

export { Vault };


/**
 * Autogenerated file, do not edit manually. @see https://github.com/reconmap/model-definitions
 */
const defaultVault : Vault = {

	id: undefined,
	insert_ts: undefined,
	update_ts: undefined,
	project_id: undefined,
	type: 'password',
	name: undefined,
	value: undefined,
	note: undefined,

}

export default defaultVault;
