
interface AttachmentInterface {

	id?: number;
	parent_type: string;
	parent_id: number;
	submitter_uid: number;
	client_file_name: string;
	file_name: string;
	file_size: number;
	file_mimetype?: string;
	file_hash: string;
}


/**
 * Autogenerated file, do not edit manually. @see https://github.com/reconmap/model-definitions
 */
const Attachment : AttachmentInterface = {

	id: undefined,
}

export default Attachment;
