

interface ClientInterface {

	id?: number;
	creator_uid?: number;
	name?: string;
	address?: string;
	url?: string;
	logo_attachment_id?: number;
	small_logo_attachment_id?: number;
}

/**
 * Autogenerated file, do not edit manually. @see https://github.com/reconmap/pocoglot-definitions
 */
const Client : ClientInterface = {

	logo_attachment_id: undefined,
	small_logo_attachment_id: undefined,
}

export default Client;
