
interface CommandScheduleInterface {

	id?: number;
	creator_uid?: number;
	command_id?: number;
	argument_values?: string;
	cron_expression?: string;
}


/**
 * Autogenerated file, do not edit manually. @see https://github.com/reconmap/model-definitions
 */
const CommandSchedule : CommandScheduleInterface = {

}

export default CommandSchedule;
