
interface CommandInterface {

	id?: number;
	creator_uid?: number;
	name?: string;
	output_parser?: string;
	description?: string;
	executable_type?: string;
	executable_path?: string;
	docker_image?: string;
	arguments?: string;
	output_filename?: string;
	more_info_url?: string;
	tags?: string;
}


/**
 * Autogenerated file, do not edit manually. @see https://github.com/reconmap/model-definitions
 */
const Command : CommandInterface = {

	executable_type: 'custom',
}

export default Command;
