
interface CommandSchedule {

	id?: number;
	creator_uid?: number;
	command_id?: number;
	argument_values?: string;
	cron_expression?: string;
}

export { CommandSchedule };


/**
 * Autogenerated file, do not edit manually. @see https://github.com/reconmap/model-definitions
 */
const defaultCommandSchedule : CommandSchedule = {


}

export default defaultCommandSchedule;
