
interface CommandUsageInterface {

	id?: number;
	command_id?: number;
	creator_uid?: number;
	description?: string;
	executable_type?: string;
	executable_path?: string;
	docker_image?: string;
	arguments?: string;
	output_filename?: string;
	output_parser?: string;
}


/**
 * Autogenerated file, do not edit manually. @see https://github.com/reconmap/model-definitions
 */
const CommandUsage : CommandUsageInterface = {

	executable_type: 'custom',
}

export default CommandUsage;
