
interface ContactInterface {

	id?: number;
	kind: string;
	name?: string;
	email?: string;
	phone?: string;
	role?: string;
}


/**
 * Autogenerated file, do not edit manually. @see https://github.com/reconmap/pocoglot-definitions
 */
const Contact : ContactInterface = {

	id: undefined,
	kind: 'general',
	name: undefined,
	email: undefined,
	phone: undefined,
	role: undefined,
}

export default Contact;
