
interface NotificationInterface {

	toUserId: number;
	title?: string;
	content: string;
}


/**
 * Autogenerated file, do not edit manually. @see https://github.com/reconmap/model-definitions
 */
const Notification : NotificationInterface = {

}

export default Notification;
