
interface Notification {

	toUserId: number | undefined;
	title?: string;
	content: string | undefined;
}

export { Notification };


/**
 * Autogenerated file, do not edit manually. @see https://github.com/reconmap/model-definitions
 */
const defaultNotification : Notification = {


	toUserId: undefined,
	content: undefined,
}

export default defaultNotification;
