
interface OrganisationInterface {

	id?: number;
	name: string;
	url?: string;
	contact_name?: string;
	contact_email?: string;
	contact_phone?: string;
	logo_attachment_id?: number;
	small_logo_attachment_id?: number;
}


/**
 * Autogenerated file, do not edit manually. @see https://github.com/reconmap/model-definitions
 */
const Organisation : OrganisationInterface = {

	id: undefined,
	name: '',
	url: undefined,
	contact_name: undefined,
	contact_email: undefined,
	contact_phone: undefined,
	logo_attachment_id: undefined,
	small_logo_attachment_id: undefined,
}

export default Organisation;
