
interface Organisation {

	id?: number;
	insert_ts?: string;
	update_ts?: string;
	name: string | undefined;
	url?: string;
	contact_id?: number;
	contact_name?: string;
	contact_email?: string;
	contact_phone?: string;
	logo_attachment_id?: number;
	small_logo_attachment_id?: number;
}

export { Organisation };


/**
 * Autogenerated file, do not edit manually. @see https://github.com/reconmap/model-definitions
 */
const defaultOrganisation : Organisation = {

	id: undefined,
	name: '',
	url: undefined,
	contact_id: undefined,
	contact_name: undefined,
	contact_email: undefined,
	contact_phone: undefined,
	logo_attachment_id: undefined,
	small_logo_attachment_id: undefined,

}

export default defaultOrganisation;
