
interface Report {

	id?: number;
	projectId?: number;
	generatedByUid?: number;
	is_template?: boolean;
	insertTs?: string;
	versionName?: string;
	versionDescription?: string;
}

export { Report };


/**
 * Autogenerated file, do not edit manually. @see https://github.com/reconmap/model-definitions
 */
const defaultReport : Report = {

	id: undefined,
	projectId: undefined,
	generatedByUid: undefined,
	is_template: false,
	insertTs: undefined,
	versionName: undefined,
	versionDescription: undefined,

}

export default defaultReport;
