
interface ReportConfigurationInterface {

	id: number;
	project_id: number;
	include_toc: boolean;
	include_revisions_table: boolean;
	include_team_bios: boolean;
	include_findings_overview: boolean;
	include_cover: string;
	include_header: string;
	include_footer: string;
	custom_cover?: string;
	custom_header?: string;
	custom_footer?: string;
}


/**
 * Autogenerated file, do not edit manually. @see https://github.com/reconmap/model-definitions
 */
const ReportConfiguration : ReportConfigurationInterface = {

	include_toc: true,
	include_revisions_table: true,
	include_team_bios: true,
	include_findings_overview: true,
	include_cover: 'default',
	include_header: 'default',
	include_footer: 'default',
}

export default ReportConfiguration;
