
interface TargetInterface {

	project_id: number;
	parent_id?: number;
	name: string;
	kind: string;
	tags?: string;
}


/**
 * Autogenerated file, do not edit manually. @see https://github.com/reconmap/model-definitions
 */
const Target : TargetInterface = {

	parent_id: undefined,
}

export default Target;
