
interface VaultInterface {

	id?: number;
	insert_ts?: string;
	update_ts?: string;
	name?: string;
	value?: string;
	reportable?: boolean;
	note?: string;
	type: string;
	project_id?: number;
}


/**
 * Autogenerated file, do not edit manually. @see https://github.com/reconmap/model-definitions
 */
const Vault : VaultInterface = {

	id: undefined,
	insert_ts: undefined,
	update_ts: undefined,
	name: undefined,
	value: undefined,
	reportable: false,
	note: undefined,
	type: 'password',
	project_id: undefined,
}

export default Vault;
